name: Build for MT7621a (Fixed)

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Clean disk space
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc

    - name: Setup OpenWrt SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev git subversion python3 unzip
        wget https://downloads.openwrt.org/releases/22.03.3/targets/ramips/mt7621/openwrt-sdk-22.03.3-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64.tar.xz
        tar -xvf openwrt-sdk-*.tar.xz
        mv openwrt-sdk-* sdk

    - name: Prepare QModem
      run: |
        mkdir -p sdk/package/qmodem
        cp -r $GITHUB_WORKSPACE/* sdk/package/qmodem/
        rm -rf sdk/package/qmodem/.github
        ls -l sdk/package/qmodem/  # 调试用

    - name: Compile
      run: |
        cd sdk
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        make package/qmodem/compile V=s 2>&1 | tee build.log  # 保存详细日志
        grep -i error build.log && exit 1  # 如果日志中有error则主动报错

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: |
          sdk/bin/packages/*/*.ipk
          sdk/build.log
