#!/bin/bash
set -e  # 关键：遇到错误立即退出

# 1. 设置mt7621专用SDK
SDK_NAME="openwrt-sdk-22.03.3-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64"
SDK_URL="https://downloads.openwrt.org/releases/22.03.3/targets/ramips/mt7621/"
wget "${SDK_URL}/${SDK_NAME}.tar.xz"
tar xf ${SDK_NAME}.tar.xz
mv ${SDK_NAME} sdk

# 2. 设置交叉编译环境
export STAGING_DIR=$(pwd)/sdk/staging_dir
TOOLCHAIN_DIR=$(find $STAGING_DIR -name "toolchain-mipsel_*" -type d)
export PATH=$TOOLCHAIN_DIR/bin:$PATH

# 3. 验证工具链
mipsel-openwrt-linux-gcc --version || {
    echo "❌ 交叉编译工具链验证失败";
    exit 1;
}

# 4. 编译（示例）
cd package/qmodem
make CC=mipsel-openwrt-linux-gcc
