name: Build QModem for MT7621a (Fixed)

on:
  workflow_dispatch:
  push:
    branches: ["main"]

env:
  SDK_URL: "https://downloads.openwrt.org/releases/22.03.3/targets/ramips/mt7621/openwrt-sdk-22.03.3-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64.tar.xz"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: "src"  # 关键修改：指定检出目录

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libncurses5-dev \
            zlib1g-dev \
            rsync

      - name: Download and extract SDK
        run: |
          wget -T 60 "${{ env.SDK_URL }}" -O sdk.tar.xz
          tar -xvf sdk.tar.xz
          mv openwrt-sdk-* sdk
          echo "SDK_PATH=$(pwd)/sdk" >> $GITHUB_ENV

      - name: Prepare package
        run: |
          # 创建标准OpenWrt包结构
          PKG_DIR="${{ env.SDK_PATH }}/package/qmodem"
          mkdir -p "$PKG_DIR"
          
          # 复制必要的文件（根据实际项目结构调整）
          cp -r src/application "$PKG_DIR/"
          cp src/Makefile "$PKG_DIR/"  # 确保Makefile存在
          
          # 验证关键文件
          [ -f "$PKG_DIR/Makefile" ] || {
            echo "::error::Makefile still missing!"
            echo "Current package contents:"
            tree "$PKG_DIR"
            exit 1
          }

      - name: Compile
        env:
          TERM: dumb
        run: |
          cd "${{ env.SDK_PATH }}"
          
          # 初始化环境
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
          # 强制启用包
          echo "CONFIG_PACKAGE_qmodem=y" > .config
          
          # 编译
          make package/qmodem/compile V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ipk-package
          path: "${{ env.SDK_PATH }}/bin/packages/*/*.ipk"
