- name: Download SDK (Fixed)
  id: download_sdk
  env:
    PRIMARY_URL: "https://downloads.openwrt.org/releases/22.03.3/targets/ramips/mt7621/openwrt-sdk-22.03.3-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64.tar.xz"
    BACKUP_URL: "https://mirror.0x.si/openwrt/releases/22.03.3/targets/ramips/mt7621/openwrt-sdk-22.03.3-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64.tar.xz"
  run: |
    max_retries=3
    retry_delay=10
    sdk_file="openwrt-sdk.tar.xz"

    # 主镜像下载尝试
    for ((i=1; i<=$max_retries; i++)); do
      echo "Attempt $i: Downloading from primary mirror..."
      if wget -T 60 -O "$sdk_file" "$PRIMARY_URL"; then
        if [ $(stat -c%s "$sdk_file") -gt 100000000 ]; then
          echo "Download successful!"
          exit 0
        else
          echo "File size too small, may be corrupted"
          rm -f "$sdk_file"
        fi
      fi
      sleep $retry_delay
    done

    # 备用镜像尝试
    echo "Trying fallback mirror..."
    if ! wget -T 120 -O "$sdk_file" "$BACKUP_URL"; then
      echo "::error::All download attempts failed"
      exit 1
    fi

    # 最终验证
    if [ $(stat -c%s "$sdk_file") -lt 100000000 ]; then
      echo "::error::Downloaded file is too small (likely incomplete)"
      exit 1
    fi
