name: Build QModem (Non-Interactive)

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev
          echo "TERM=dumb" >> $GITHUB_ENV

      - name: Download SDK
        run: |
          wget https://downloads.openwrt.org/releases/22.03.3/targets/ramips/mt7621/openwrt-sdk-22.03.3-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64.tar.xz
          tar -xvf openwrt-sdk-*.tar.xz
          mv openwrt-sdk-* sdk
          echo "SDK_PATH=$(pwd)/sdk" >> $GITHUB_ENV

      - name: Prepare package
        run: |
          mkdir -p "${{ env.SDK_PATH }}/package/qmodem"
          rsync -av --exclude='sdk' "$GITHUB_WORKSPACE/" "${{ env.SDK_PATH }}/package/qmodem/"

      - name: Compile
        run: |
          cd "${{ env.SDK_PATH }}"
          
          # 非交互式配置
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cat <<EOF > .config
CONFIG_PACKAGE_qmodem=y
CONFIG_PACKAGE_libopenssl=y
EOF
          
          # 强制非交互式编译
          make -j$(nproc) package/qmodem/compile V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ipk-package
          path: "${{ env.SDK_PATH }}/bin/packages/*/*.ipk"
