name: Build QModem (Fixed Structure)

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Validate repository structure
        run: |
          if [ ! -f "Makefile" ] && [ ! -f "src/Makefile" ]; then
            echo "::error::No Makefile found in root or src directory"
            echo "Please create an OpenWrt package Makefile"
            exit 1
          fi
          echo "Repository structure validated"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libncurses5-dev \
            zlib1g-dev \
            rsync

      - name: Download and extract SDK
        run: |
          wget -T 60 "${{ env.SDK_URL }}" -O sdk.tar.xz
          tar -xvf sdk.tar.xz
          mv openwrt-sdk-* sdk
          echo "SDK_PATH=$(pwd)/sdk" >> $GITHUB_ENV

      - name: Prepare package
        run: |
         PKG_DIR="${{ env.SDK_PATH }}/package/qmodem"
         mkdir -p "$PKG_DIR"
    
         # 复制整个仓库内容（排除.git等目录）
         rsync -av \
         --exclude='.git' \
         --exclude='.github' \
         --exclude='sdk' \
         "$GITHUB_WORKSPACE/" "$PKG_DIR/"
    
         # 检查Makefile是否存在（支持多个可能位置）
         if [ ! -f "$PKG_DIR/Makefile" ]; then
         echo "::warning::Checking alternative locations for Makefile"
         # 尝试在src目录查找
         if [ -f "$PKG_DIR/src/Makefile" ]; then
         cp "$PKG_DIR/src/Makefile" "$PKG_DIR/"
         # 尝试在根目录查找
         elif [ -f "$GITHUB_WORKSPACE/Makefile" ]; then
         cp "$GITHUB_WORKSPACE/Makefile" "$PKG_DIR/"
         else
         echo "::error::Makefile not found in any standard location"
         echo "Current package contents:"
         tree "$PKG_DIR"
         exit 1
         fi
         fi
    
         # 最终验证
         [ -f "$PKG_DIR/Makefile" ] || exit 1
         echo "Makefile found at: $(realpath "$PKG_DIR/Makefile")"

      - name: Compile
        env:
          TERM: dumb
        run: |
          cd "${{ env.SDK_PATH }}"
          
          # 初始化环境
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
          # 强制启用包
          echo "CONFIG_PACKAGE_qmodem=y" > .config
          
          # 编译
          make package/qmodem/compile V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ipk-package
          path: "${{ env.SDK_PATH }}/bin/packages/*/*.ipk"
