name: Build QModem for OpenWrt (Fixed)

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Download SDK
        run: |
          wget -O sdk.tar.xz "https://downloads.openwrt.org/releases/22.03.3/targets/ramips/mt7621/openwrt-sdk-22.03.3-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64.tar.xz"
          tar -xvf sdk.tar.xz
          mv openwrt-sdk-* sdk
          echo "SDK_PATH=$(pwd)/sdk" >> $GITHUB_ENV

      - name: Prepare package
        run: |
          mkdir -p "${{ env.SDK_PATH }}/package/qmodem"
          cp -r application "${{ env.SDK_PATH }}/package/qmodem/src"
          
          # 创建标准Makefile
          cat > "${{ env.SDK_PATH }}/package/qmodem/Makefile" <<'EOF'
          include $(TOPDIR)/rules.mk

          PKG_NAME:=qmodem
          PKG_VERSION:=1.0
          PKG_RELEASE:=1

          include $(INCLUDE_DIR)/package.mk

          define Package/qmodem
            SECTION:=utils
            CATEGORY:=Utilities
            TITLE:=QModem Utility
            DEPENDS:=+libopenssl
          endef

          define Build/Compile
            $(MAKE) -C $(PKG_BUILD_DIR)/src \
              $(TARGET_CONFIGURE_OPTS) \
              CFLAGS="$(TARGET_CFLAGS)"
          endef

          $(eval $(call BuildPackage,qmodem))
          EOF

      - name: Compile
        run: |
          cd "${{ env.SDK_PATH }}"
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          echo "CONFIG_PACKAGE_qmodem=y" > .config
          make package/qmodem/compile V=s

      - name: Upload IPK
        uses: actions/upload-artifact@v4
        with:
          name: qmodem-ipk
          path: |
            ${{ env.SDK_PATH }}/bin/packages/*/base/qmodem_*.ipk
            ${{ env.SDK_PATH }}/compile.log
          if-no-files-found: error
